# Generated by Django 3.2.18 on 2023-03-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arabicafood', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
